# Generated by Django 3.0.5 on 2020-04-13 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('industry', models.CharField(choices=[('FA', 'Finance and Accounting'), ('MA', 'Marketing'), ('DE', 'Design'), ('DS', 'Data Analytics and Stats'), ('PS', 'Programming and Software'), ('SC', 'Supply Chain'), ('FS', 'Fashion'), ('CO', 'Communications'), ('FB', 'Food and Beverage'), ('RE', 'Research')], max_length=2, verbose_name='Industry')),
                ('typeOfBusiness', models.CharField(max_length=50, verbose_name='Type of Business')),
                ('website', models.URLField()),
                ('phone', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('highSchool', models.CharField(max_length=50, verbose_name='High School')),
                ('year', models.CharField(choices=[('HS', 'High School'), ('BA', 'Bachelors'), ('MA', 'Masters')], max_length=2)),
                ('dob', models.DateField()),
                ('phone', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('location', models.CharField(default='Remote', max_length=50)),
                ('startDate', models.DateField(verbose_name='Start Date')),
                ('qualification', models.CharField(choices=[('HS', 'High School'), ('BA', 'Bachelors'), ('MA', 'Masters')], max_length=2)),
                ('stipend', models.BooleanField()),
                ('description', models.TextField(max_length=2000)),
                ('requirements', models.TextField(max_length=2000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='')),
                ('cover', models.FileField(upload_to='')),
                ('skills', models.TextField(max_length=500)),
                ('presence', models.URLField()),
                ('approved', models.BooleanField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Post')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Student')),
            ],
            options={
                'verbose_name_plural': 'Applications',
            },
        ),
    ]
