# Generated by Django 3.0.5 on 2020-04-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='presence',
            field=models.URLField(blank=True, null=True),
        ),
    ]
