# Generated by Django 3.0.5 on 2020-04-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='companyLogo',
        ),
        migrations.AddField(
            model_name='company',
            name='companyLogo',
            field=models.ImageField(default='images/115x115.gif', upload_to=''),
        ),
    ]
