# Generated by Django 3.0.5 on 2020-04-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='approved',
        ),
        migrations.AddField(
            model_name='apply',
            name='status',
            field=models.CharField(choices=[('QR', 'Quar.in'), ('WC', 'With company'), ('AP', 'Approved'), ('RJ', 'Rejected')], default='QR', max_length=2),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Company name'),
        ),
    ]
