# Generated by Django 3.0.5 on 2020-04-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20200415_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='company',
        ),
        migrations.AlterField(
            model_name='company',
            name='companyLogo',
            field=models.ImageField(default='images/115x115.gif', upload_to='', verbose_name='Company Logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('FA', 'Finance and Accounting'), ('MA', 'Marketing'), ('DE', 'Design'), ('DS', 'Data Analytics and Stats'), ('PS', 'Programming and Software'), ('SC', 'Supply Chain'), ('FS', 'Fashion'), ('CO', 'Communications'), ('FB', 'Food and Beverage'), ('RE', 'Research'), ('OT', 'Other')], max_length=2, verbose_name='Industry'),
        ),
    ]
